import { createRemoteJWKSet, jwtVerify } from 'jose';

export const clientId = process.env.EVE_CLIENT_ID || '2e10fc765f9a4fda978476d369d0b04f';
export const scopes = ['esi-wallet.read_character_wallet.v1','esi-skills.read_skillqueue.v1','esi-industry.read_character_jobs.v1','esi-location.read_location.v1','esi-clones.read_clones.v1','esi-universe.read_structures.v1','esi-contracts.read_character_contracts.v1','esi-markets.read_character_orders.v1'];
const metadataUrl = 'https://login.eveonline.com/.well-known/oauth-authorization-server';
const encoder = new TextEncoder();

export type Session = {characterId:string;name:string;accessToken:string;refreshToken:string;expiresAt:number};
export type StoredCharacter={characterId:string;name:string;refreshToken:string};
export type MultiSession={activeCharacterId:string;characters:StoredCharacter[]};
let metadata:Record<string,string>|null=null;let jwks:ReturnType<typeof createRemoteJWKSet>|null=null;
const b64=(data:ArrayBuffer|Uint8Array)=>Buffer.from(data instanceof ArrayBuffer?new Uint8Array(data):data).toString('base64url');

async function key(){const secret=process.env.SESSION_SECRET;if(!secret)throw new Error('SESSION_SECRET fehlt');const digest=await crypto.subtle.digest('SHA-256',encoder.encode(secret));return crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt','decrypt'])}
export async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),encoder.encode(JSON.stringify(value)));return `${b64(iv)}.${b64(encrypted)}`}
export async function unseal<T>(value?:string):Promise<T|null>{try{if(!value)return null;const[iv,data]=value.split('.').map(part=>Buffer.from(part,'base64url'));const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv},await key(),data);return JSON.parse(new TextDecoder().decode(clear)) as T}catch{return null}}
export async function getMetadata(){if(metadata)return metadata;const response=await fetch(metadataUrl,{next:{revalidate:300}});if(!response.ok)throw new Error('EVE SSO nicht erreichbar');metadata=await response.json() as Record<string,string>;jwks=createRemoteJWKSet(new URL(metadata.jwks_uri));return metadata}
export async function tokenRequest(parameters:Record<string,string>){const meta=await getMetadata();const response=await fetch(meta.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(parameters),cache:'no-store'});if(!response.ok){const detail=(await response.text()).slice(0,300).replace(/[\r\n]/g,' ');throw new Error(`EVE Tokenfehler ${response.status}: ${detail}`)}return response.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number}>}
export async function verifyToken(token:string){await getMetadata();const{payload}=await jwtVerify(token,jwks!,{issuer:['https://login.eveonline.com/','https://login.eveonline.com','login.eveonline.com'],audience:clientId});const audiences=Array.isArray(payload.aud)?payload.aud:[payload.aud];if(!audiences.includes(clientId)||!audiences.includes('EVE Online'))throw new Error('Ungültige Token-Zielgruppe');const characterId=String(payload.sub||'').split(':').at(-1)||'';if(!/^\d+$/.test(characterId))throw new Error('Ungültiger Charakter');return{characterId,name:String(payload.name||'Capsuleer')}}
export async function activeToken(session:Session){if(Date.now()<session.expiresAt-30_000)return session;const tokens=await tokenRequest({grant_type:'refresh_token',refresh_token:session.refreshToken,client_id:clientId});await verifyToken(tokens.access_token);return{...session,accessToken:tokens.access_token,refreshToken:tokens.refresh_token||session.refreshToken,expiresAt:Date.now()+tokens.expires_in*1000}}
export async function refreshCharacter(character:StoredCharacter){const tokens=await tokenRequest({grant_type:'refresh_token',refresh_token:character.refreshToken,client_id:clientId});const identity=await verifyToken(tokens.access_token);if(identity.characterId!==character.characterId)throw new Error('Charakter stimmt nicht überein');return{accessToken:tokens.access_token,character:{...character,name:identity.name,refreshToken:tokens.refresh_token||character.refreshToken}}}
export function normalizeSession(value:unknown):MultiSession|null{if(!value||typeof value!=='object')return null;const data=value as Partial<MultiSession&Session>;if(Array.isArray(data.characters)){const characters=data.characters.filter((c):c is StoredCharacter=>Boolean(c&&c.characterId&&c.name&&c.refreshToken));if(!characters.length)return null;return{activeCharacterId:characters.some(c=>c.characterId===data.activeCharacterId)?String(data.activeCharacterId):characters[0].characterId,characters}}if(data.characterId&&data.name&&data.refreshToken)return{activeCharacterId:data.characterId,characters:[{characterId:data.characterId,name:data.name,refreshToken:data.refreshToken}]};return null}
export async function esi(path:string,token:string){const response=await fetch(`https://esi.evetech.net${path}`,{headers:{Authorization:`Bearer ${token}`,'X-Compatibility-Date':'2026-08-23'},cache:'no-store'});if(!response.ok)throw new Error(`ESI Fehler ${response.status}`);return response.json()}
