'use client';
import {RattingTracker} from './RattingTracker';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Goal,GoalState,day,endDate,metrics,todayUTC,validateState} from './lib/isk-goals';
type Character={characterId:string;name:string};
const isk=(n:number)=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(n)+' ISK';
const empty:GoalState={goals:[],entries:[]};
const fresh=():Goal=>({id:crypto.randomUUID(),name:'Mein ISK-Ziel',target:70000000000,start:todayUTC(),end:endDate(todayUTC(),30),characterIds:[],characterCount:7,source:'manual'});
export function IskGoals({characters}:{characters:Character[]}) {
 const [state,setState]=useState<GoalState>(empty),[revision,setRevision]=useState(0),[owner,setOwner]=useState(characters[0]?.characterId||''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[failures,setFailures]=useState<{characterId:string;name:string;message:string;reconnect:boolean}[]>([]),[draft,setDraft]=useState<Goal|null>(null),[today,setToday]=useState(todayUTC());
 const saving=useRef(false);
 const loadRequest=useRef(0);
 const load=useCallback(async(id=owner)=>{const request=++loadRequest.current;try{const r=await fetch(`/api/isk-goals?owner=${id}`,{cache:'no-store'});const data=await r.json() as {state:GoalState;revision:number;error:string;note:string;failures?:{characterId:string;name:string;message:string;reconnect:boolean}[]};if(request!==loadRequest.current)return;if(!r.ok)throw new Error(data.error);setState(data.state);setRevision(data.revision);setLoaded(true);setNotice('');setFailures([]);}catch(e){if(request===loadRequest.current){setLoaded(false);setNotice(e instanceof Error?e.message:'Laden fehlgeschlagen.');}}},[owner]);
 // The loader updates state only after the external fetch completes (or fails).
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load();const timer=setInterval(()=>setToday(todayUTC()),60000);return()=>clearInterval(timer);},[load]);
 const save=async(next:GoalState,action='save')=>{if(saving.current)return false;saving.current=true;setBusy(true);try{validateState(next);const r=await fetch(`/api/isk-goals?owner=${owner}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:next,revision,action})});const data=await r.json() as {state:GoalState;revision:number;error:string;note:string;failures?:{characterId:string;name:string;message:string;reconnect:boolean}[]};if(!r.ok)throw new Error(data.error);setState(data.state);setRevision(data.revision);setNotice(data.note);setFailures(data.failures||[]);return true;}catch(e){setNotice(e instanceof Error?e.message:'Speichern fehlgeschlagen.');return false;}finally{saving.current=false;setBusy(false);}};
 const activateEsi=()=>{if(state.goals.some(g=>g.source==='esi')){void save(state,'sync');return;}const g=state.goals[0]||fresh();setDraft({...g,source:'esi',characterIds:g.characterIds.length?g.characterIds:characters.map(c=>c.characterId)});setNotice('ESI-Ziel prüfen und speichern. Danach Einnahmen aktualisieren. Manuelle Einträge bleiben gespeichert und zählen im ESI-Modus nicht mit.');};
 const update=(patch:Partial<Goal>)=>setDraft(d=>d?{...d,...patch}:null);
 return <section className="isk-goals" id="isk-ziele" aria-labelledby="isk-title"><header><div><p className="section-label">DEIN NÄCHSTES ZIEL</p><h2 id="isk-title">ISK-Ziele</h2></div><button disabled={!loaded||busy} onClick={()=>setDraft(fresh())}>＋ Ziel erstellen</button></header>
 <label className="isk-owner">Ziele gespeichert bei <select value={owner} disabled={busy} onChange={e=>{setLoaded(false);setDraft(null);setOwner(e.target.value);}}>{characters.map(c=><option key={c.characterId} value={c.characterId}>{c.name}</option>)}</select></label>
 <p className="isk-help">Serverseitig gespeichert. Auf einem anderen Gerät denselben Speicher-Charakter verbinden und auswählen. Alle Tage gelten in EVE-Zeit (UTC), Start- und Endtag zählen mit.</p>
 <div className="isk-actions"><button disabled={!loaded||busy} onClick={activateEsi}>{busy?'Bitte warten…':'ESI-Einnahmen aktualisieren'}</button><button disabled={busy} onClick={()=>load()}>Neu laden</button></div>
 {notice&&<p role="status" className="isk-notice">{notice}</p>}{failures.length>0&&<div role="alert" className="isk-notice">{failures.map(f=><p key={f.characterId}><strong>{f.name}: </strong>{f.message} {f.reconnect&&<a href="/auth/eve">Mit EVE neu verbinden</a>}</p>)}</div>}
 {loaded&&<RattingTracker entries={state.entries} characters={characters} today={today} busy={busy} onSync={()=>void save(state,'sync-month')}/>}
 {!loaded&&<p>Ziele werden geladen. Bei einem Fehler bitte „Neu laden“ wählen.</p>}
 {loaded&&!state.goals.length&&!draft&&<p>Noch kein Ziel. Lege Betrag, Zeitraum und beteiligte Chars fest.</p>}
 {draft&&<form className="isk-editor" onSubmit={async e=>{e.preventDefault();const next={...state,goals:[...state.goals.filter(g=>g.id!==draft.id),draft]};if(await save(next))setDraft(null);}}><h3>{state.goals.some(g=>g.id===draft.id)?'Ziel bearbeiten':'Neues Ziel'}</h3><fieldset disabled={busy}><div className="isk-fields">
 <label>Name<input required maxLength={80} value={draft.name} onChange={e=>update({name:e.target.value})}/></label><label>Zielbetrag (ISK)<input type="number" min="0.01" max="1000000000000000" step="0.01" required value={draft.target} onChange={e=>update({target:Number(e.target.value)})}/></label>
 <label>Startdatum<input type="date" required value={draft.start} onChange={e=>update({start:e.target.value})}/></label><label>Enddatum<input type="date" required min={draft.start} value={draft.end} onChange={e=>update({end:e.target.value})}/></label>
 <label>Zeitraum (Tage)<input type="number" min="1" max="3660" required value={Number.isFinite(day(draft.end)-day(draft.start))?day(draft.end)-day(draft.start)+1:''} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>0&&n<=3660&&Number.isFinite(day(draft.start)))update({end:endDate(draft.start,n)});}}/></label>
 <label>Ist-Werte<select value={draft.source} onChange={e=>update({source:e.target.value as Goal['source']})}><option value="manual">Manuell erfasste Einnahmen</option><option value="esi">ESI: Kopfgelder + ESS</option></select></label></div>
 <p>Teilnehmende Charaktere auswählen:</p><div className="isk-chars">{characters.map(c=><label key={c.characterId}><input type="checkbox" checked={draft.characterIds.includes(c.characterId)} onChange={e=>update({characterIds:e.target.checked?[...draft.characterIds,c.characterId]:draft.characterIds.filter(id=>id!==c.characterId)})}/>{c.name}</label>)}</div>
 {!draft.characterIds.length&&<label>Anzahl Chars (manuelle Planung)<input type="number" required min="1" max="1000" value={draft.characterCount} onChange={e=>update({characterCount:Number(e.target.value)})}/></label>}
 {draft.source==='esi'&&<p className="isk-help">Kopfgeld- und ESS-Auszahlungen zählen. Player Donations, Marktverkäufe und andere Buchungsarten werden ausgeschlossen. Regelmäßig importieren: ESI stellt ältere Journale nur begrenzt bereit. Manuelle Werte zählen in diesem Modus nicht mit.</p>}
 {day(draft.end)>=day(draft.start)&&<p>{isk(draft.target/(day(draft.end)-day(draft.start)+1))} / Tag · {isk(draft.target/(day(draft.end)-day(draft.start)+1)/(draft.characterIds.length||draft.characterCount))} / Char</p>}
 <div className="isk-actions"><button type="submit">Ziel speichern</button><button type="button" onClick={()=>setDraft(null)}>Abbrechen</button></div></fieldset></form>}
 {loaded&&state.goals.map(g=>{const m=metrics(g,state.entries,today);return <article className="isk-goal" key={g.id}><header><div><h3>{g.name}</h3><p>{g.start} – {g.end} · {m.count} Chars · {g.source==='esi'?'ESI-Kopfgelder + ESS':'Manuell'}</p></div><button disabled={busy} onClick={()=>setDraft({...g})}>Bearbeiten</button></header>
 <strong className="isk-total">{isk(m.actual)} <span>von {isk(g.target)}</span></strong><progress max="100" value={m.progress} aria-label={`Zielfortschritt ${m.progress.toFixed(1)} Prozent`}/><p>{m.progress.toFixed(1)} % erreicht · Restbetrag {isk(m.remaining)}</p>
 <div className="isk-stats">{[['Tagesziel gesamt',isk(m.daily)],['Tagesziel pro Char',isk(m.perCharacter)],['Heute Soll',isk(m.todayTarget)],['Heute Ist',isk(m.todayActual)],['Heute noch offen',isk(m.todayRemaining)],['Heute Abweichung',isk(m.todayActual-m.todayTarget)],['Benötigt pro verbleibendem Tag',m.needed===null?'Zeitraum abgelaufen':isk(m.needed)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <p className={m.deviation>=0?'isk-ahead':'isk-behind'}>{m.deviation>=0?'Vor':'Hinter'} Soll: {isk(Math.abs(m.deviation))} · Soll bis Ende heute · {m.remainingDays} verbleibende Tage einschließlich heute</p>
 {g.source==='esi'&&<details><summary>Einnahmen je Charakter</summary>{g.characterIds.map(id=>{const c=metrics({...g,characterIds:[id]},state.entries,today);return <p key={id}>{characters.find(x=>x.characterId===id)?.name||id}: heute {isk(c.todayActual)} · gesamt {isk(c.actual)}</p>;})}</details>}
 {g.source==='manual'&&<form className="isk-entry" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const entry={id:crypto.randomUUID(),goalId:g.id,source:'manual' as const,date:String(f.get('date')),amount:Number(f.get('amount')),characterId:String(f.get('characterId')||'')};if(await save({...state,entries:[...state.entries,entry]}))form.reset();}}><h4>Einnahme hinzufügen</h4><fieldset disabled={busy}><div className="isk-fields"><label>Datum<input name="date" type="date" min={g.start} max={g.end<today?g.end:today} defaultValue={today<g.start?g.start:today>g.end?g.end:today} required/></label><label>Betrag (ISK; Korrekturen auch negativ)<input name="amount" type="number" step="0.01" max="1000000000000000" min="-1000000000000000" required/></label>{g.characterIds.length>0&&<label>Charakter<select name="characterId">{g.characterIds.map(id=><option key={id} value={id}>{characters.find(c=>c.characterId===id)?.name||id}</option>)}</select></label>}</div><button disabled={today<g.start}>Einnahme speichern</button></fieldset></form>}
 {g.source==='manual'&&<details><summary>Manuelle Einträge verwalten</summary>{state.entries.filter(e=>e.goalId===g.id).sort((a,b)=>b.date.localeCompare(a.date)).map(entry=><div className="isk-entry-row" key={entry.id}><span>{entry.date} · {isk(entry.amount)} {characters.find(c=>c.characterId===entry.characterId)?.name}</span><button disabled={busy} onClick={()=>{if(confirm('Diesen Eintrag löschen?'))void save({...state,entries:state.entries.filter(e=>e.id!==entry.id)});}}>Entfernen</button></div>)}</details>}
 <button className="isk-delete" disabled={busy} onClick={()=>{if(confirm('Ziel und zugehörige manuelle Einträge löschen?'))void save({goals:state.goals.filter(x=>x.id!==g.id),entries:state.entries.filter(e=>e.goalId!==g.id)});}}>Ziel löschen</button></article>;})}</section>;
}



