import {test} from 'node:test';import assert from 'node:assert/strict';
import {readTransactions,tradingTotals,jitaPrices} from '../app/lib/trading.ts';
const row={transaction_id:10,date:'2026-10-08T01:00:00Z',is_buy:false,is_personal:true,quantity:3,unit_price:10,type_id:34};
test('UTC date, personal trades, deduplication, sales and purchases',()=>{const rows=[row,row,{...row,transaction_id:9,is_buy:true,quantity:2},{...row,transaction_id:8,is_personal:false},{...row,transaction_id:7,date:'2026-10-07T23:59:59Z'},{...row,transaction_id:6,date:'2026-09-30T23:59:59Z'}];assert.deepEqual(tradingTotals(rows,'2026-10-08'),{sales:30,purchases:20,net:10,count:2});assert.equal(tradingTotals(rows,'2026-10').sales,60);assert.equal(tradingTotals([],'2026-10').net,0);});
test('from_id includes boundary row without double counting',async()=>{const urls=[];const pages=[[row,{...row,transaction_id:9}],[{...row,transaction_id:9},{...row,transaction_id:8}],[{...row,transaction_id:8}]];const result=await readTransactions('1','token',async url=>{urls.push(url);return Response.json(pages.shift());});assert.equal(result.length,3);assert.match(urls[1],/from_id=9/);assert.match(urls[2],/from_id=8/);});
test('empty history and cursor failure',async()=>{assert.deepEqual(await readTransactions('1','token',async()=>Response.json([])),[]);await assert.rejects(readTransactions('1','token',async()=>Response.json([row,{...row,transaction_id:9}])));});
test('scope and upstream failures fail closed',async()=>{for(const status of [401,403,429,503])await assert.rejects(readTransactions('1','token',async()=>new Response('',{status})),e=>e.reconnect===[401,403].includes(status));});
test('invalid row rejected',async()=>{await assert.rejects(readTransactions('1','token',async()=>Response.json([{...row,quantity:-5}])));});
test('only selected item at Jita 4-4; empty sides stay null',()=>{const o={type_id:34,location_id:60003760,volume_remain:100,is_buy_order:false,price:7};assert.deepEqual(jitaPrices([o,{...o,is_buy_order:true,price:5},{...o,price:1,location_id:60000000},{...o,price:1,type_id:35},{...o,price:1,volume_remain:0}],34),{buy:5,sell:7,buyVolume:100,sellVolume:100,spread:2});assert.equal(jitaPrices([],34).sell,null);});
