import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readWalletJournal,WalletError} from '../app/lib/wallet-journal.ts';
import {journalIncome,isEarnedIncome,metrics} from '../app/lib/isk-goals.ts';
const row={id:5,date:'2026-09-09T01:00:00Z',amount:100,ref_type:'bounty_prizes',first_party_id:999,second_party_id:1};
test('Alle Journal-Seiten und wiederholter Import ohne Doppelzählung',async()=>{const pages=[];const rows=await readWalletJournal('1','test',async url=>{pages.push(url);return Response.json([row],{headers:{'X-Pages':'2'}});});assert.equal(pages.length,2);assert.match(pages[1],/page=2/);assert.equal(new Map(journalIncome(rows,'1',['1']).map(e=>[e.id,e])).size,1);});
for(const status of [401,403,420,429,500])test(`ESI ${status} liefert verständlichen Fehler`,async()=>{await assert.rejects(readWalletJournal('1','test',async()=>new Response('',{status})),e=>e instanceof WalletError&&e.reconnect===[401,403].includes(status));});
test('Keine unvollständige Übernahme bei fehlerhafter Folgeseite',async()=>{let page=0;await assert.rejects(readWalletJournal('1','test',async()=>++page===1?Response.json([row],{headers:{'X-Pages':'2'}}):new Response('',{status:503})));});
test('Fehlendes Token, Netzwerkfehler und ungültige Seitenzahl',async()=>{await assert.rejects(readWalletJournal('1',''),e=>e.reconnect);await assert.rejects(readWalletJournal('1','test',async()=>{throw Error('network');}));await assert.rejects(readWalletJournal('1','test',async()=>Response.json([row],{headers:{'X-Pages':'101'}})));});
test('Kopfgelder und ESS zählen, andere Einnahmen nicht',()=>{const types=['market_escrow','contract_collateral_refund','agent_mission_collateral_refunded','freelance_jobs_escrow_refund','contract_reversal','flux_ticket_repayment','bounty_prizes','ess_escrow_transfer','market_transaction'];assert.deepEqual(journalIncome(types.map((ref_type,id)=>({...row,id,ref_type})),'1',['1']).map(e=>e.refType),['bounty_prizes','ess_escrow_transfer']);});
test('Später verbundener eigener Transferpartner wird auch im gespeicherten Journal erkannt',()=>{const entry={amount:100,refType:'player_donation',firstPartyId:'2',secondPartyId:'1'};assert.equal(isEarnedIncome(entry,['1']),false);assert.equal(isEarnedIncome(entry,['1','2']),false);});
test('Heute offen sinkt mit ESI-Einnahmen und wird nie negativ',()=>{const goal={id:'g',name:'Test',target:200,start:'2026-09-09',end:'2026-09-10',characterIds:['1'],characterCount:1,source:'esi'};assert.equal(metrics(goal,[],'2026-09-09').todayRemaining,100);assert.equal(metrics(goal,journalIncome([row],'1',['1']),'2026-09-09').todayRemaining,0);});
test('Kopfgeld mit identischem Charakter auf beiden Buchungsseiten zählt heute',()=>{const entries=journalIncome([{...row,first_party_id:1,second_party_id:1}],'1',['1','2']);const goal={id:'g',name:'Kopfgeld',target:1000,start:'2026-09-09',end:'2026-09-09',characterIds:['1'],characterCount:1,source:'esi'};assert.equal(entries.length,1);assert.equal(metrics(goal,entries,'2026-09-09').todayActual,100);assert.equal(metrics(goal,entries,'2026-09-09').todayRemaining,900);});

test('Donations, unbekannte Altimporte und andere Einnahmen werden ausgeschlossen',()=>{for(const refType of ['player_donation','market_transaction','agent_mission_reward',undefined])assert.equal(isEarnedIncome({amount:100,refType},[]),false);for(const refType of ['bounty_prize','bounty_prizes','ess_escrow_transfer'])assert.equal(isEarnedIncome({amount:100,refType},[]),true);});

test('ESS aktualisiert Tageswert und Fortschritt ohne Donations und Doppelzählung',()=>{const rows=[{...row,id:1,amount:60},{...row,id:2,amount:40,ref_type:'ess_escrow_transfer'},{...row,id:3,amount:500,ref_type:'player_donation'}];const imported=journalIncome(rows,'1',['1']);const entries=[...new Map([...imported,...imported].map(e=>[e.id,e])).values()];const goal={id:'g',name:'Test',target:200,start:'2026-09-09',end:'2026-09-09',characterIds:['1'],characterCount:1,source:'esi'};const m=metrics(goal,entries,'2026-09-09');assert.equal(m.todayActual,100);assert.equal(m.progress,50);assert.equal(m.todayRemaining,100);assert.equal(isEarnedIncome({amount:-40,refType:'ess_escrow_transfer'},[]),false);});
