const {test}=require('node:test'),assert=require('node:assert/strict');
const {parseLine,localSystem,entities,isClear,friendly,shipCounts,decoder}=require('./intel-core.cjs');
const {IntelService}=require('./intel-service.cjs');
const systems=require('./system-catalog.json'),ships=require('./ship-names.json');
test('user format: system, pilot, ship',()=>{const r=entities('WMH-SO Erwin Thorax',systems,ships);assert.equal(r.systems[0].name,'WMH-SO');assert.deepEqual(r.names,['Erwin']);assert.equal(r.reportedShip,'Thorax');const multi=entities('WMH-SO Erwin von Test Navy Omen',systems,['Navy Omen','Omen']);assert.deepEqual(multi.names,['Erwin von Test']);});
test('free chat text is not a pilot search and boundaries are exact',()=>{assert.deepEqual(entities('WMH-SO bitte passt auf die gegner auf',systems,ships).names,[]);assert.equal(entities('WMH-SO2 Erwin Thorax',systems,ships).systems.length,0);assert.equal(isClear('WMH-SO clear',[{name:'WMH-SO'}]),true);assert.equal(isClear('WMH-SO not clear',[{name:'WMH-SO'}]),false);});
test('UTF16 split chunks and UTC parsing',()=>{const text='[ 2026.10.08 08:01:02 ] Reporter > WMH-SO Erwin Thorax\r\n';const b=Buffer.concat([Buffer.from([255,254]),Buffer.from(text,'utf16le')]);const d=decoder(b);const r=parseLine((d.write(b.subarray(0,35))+d.write(b.subarray(35))+d.end()).trim());assert.equal(r.time,Date.parse('2026-10-08T08:01:02Z'));assert.equal(r.text,'WMH-SO Erwin Thorax');assert.equal(localSystem({speaker:'EVE System',text:'Channel changed to Local : Jita'}),'Jita');assert.equal(localSystem({speaker:'Pilot',text:'Channel changed to Local : Jita'}),null);});
test('friend and alliance exclusion, no alliance is not shared alliance',()=>{assert.equal(friendly({id:2,alliance_id:99},{id:1,alliance_id:99},new Set()),true);assert.equal(friendly({id:2},{id:1},new Set()),false);assert.equal(friendly({id:2},{id:1},new Set([2])),true);});
test('ships use pilot actor, deduplication and 90-day limit',()=>{const now=Date.now(),date=new Date(now-1000).toISOString();const k={killmail_id:1,killmail_time:date,victim:{character_id:9,ship_type_id:100},attackers:[{character_id:2,ship_type_id:200}]};const r=shipCounts([k,k,{...k,killmail_id:2,victim:{character_id:2,ship_type_id:300}},{...k,killmail_id:3,killmail_time:new Date(now-100*86400000).toISOString()}],2,now);assert.equal(r.samples,2);assert.deepEqual(r.ships.map(x=>x.id),[200,300]);});
function service(distance=5,alliance=8){const s=new IntelService(()=>{});s.config.autoLocation=false;s.running=true;s.generation=1;s.current={id:30000142,name:'Jita'};s.own={id:1,alliance_id:7};s.friendIds=new Set();s.distances={distance:async()=>({distance,source:"DOTLAN · Fastest Route"})};s.names=async names=>{assert.deepEqual(names,['Erwin']);return {characters:[{id:2,name:'Erwin'}]};};s.esi=async route=>route.startsWith('/route/')?Array(distance+1).fill(1):{alliance_id:route==='/characters/1/'?7:alliance};return s;}
const item=()=>({gen:1,channel:'Intel',line:{text:'WMH-SO Erwin Thorax',time:Date.now(),speaker:'Reporter'}});
test('warn at five jumps, not six; deduplication and alliance exclusion',async()=>{const s=service();await s.process(item());assert.equal(s.alerts.length,1);assert.equal(s.alerts[0].distance,5);await s.process(item());assert.equal(s.alerts.length,1);const far=service(6);await far.process(item());assert.equal(far.alerts.length,0);const blue=service(5,7);await blue.process(item());assert.equal(blue.alerts.length,0);});
test('stopped generation cannot deliver delayed alerts',async()=>{const s=service();s.generation=2;await s.process(item());assert.equal(s.alerts.length,0);});
test('new UTF16 log lines and rotation, but no historical startup alerts',async()=>{const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'eve-intel-test-'));try{const s=service();s.config={...s.config,folder:dir,channels:'intel',pilot:'Own'};s.started=Date.now()-1000;const stamp=new Date().toISOString().slice(0,19).replaceAll('-','.').replace('T',' ');const file=path.join(dir,'intel_20261008_080000.txt');const line=`[ ${stamp} ] Reporter > WMH-SO Erwin Thorax\r\n`;await fs.writeFile(file,Buffer.concat([Buffer.from([255,254]),Buffer.from('Listener: Own\r\n'+line,'utf16le')]));const got=[];s.enqueue=x=>got.push(x);await s.poll(true);assert.equal(got.length,0);await fs.appendFile(file,Buffer.from(line,'utf16le'));await s.poll();assert.equal(got.length,1);await fs.writeFile(path.join(dir,'intel_20261008_090000.txt'),Buffer.concat([Buffer.from([255,254]),Buffer.from('Listener: Own\r\n'+line,'utf16le')]));s.logNamesAt=0;await s.poll();assert.equal(got.length,2);}finally{await fs.rm(dir,{recursive:true,force:true});}});
