const {StringDecoder}=require('node:string_decoder');
function parseLine(line){const m=line.replace(/^\uFEFF/,'').match(/^\[\s*(\d{4})\.(\d{2})\.(\d{2})\s+(\d{2}):(\d{2}):(\d{2})\s*\]\s*(.*?)\s*>\s*(.*)$/);if(!m)return null;return {time:Date.parse(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`),speaker:m[7],text:m[8].trim()};}
function localSystem(line){if(!/^(EVE System|EVE-System)$/i.test(line.speaker))return null;return line.text.match(/(?:Channel changed to Local|Kanal (?:gewechselt zu|geändert auf) (?:Local|Lokal))\s*:\s*(.+)$/i)?.[1]?.trim()||null;}
function entities(text,systems,ships=[]){const clean=text.replace(/<[^>]*>/g,' ').replace(/https?:\/\/\S+/g,' ').trim();const found=[];for(const s of systems){const escaped=s.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(new RegExp(`(?<![\\p{L}\\p{N}-])${escaped}(?![\\p{L}\\p{N}-])`,'iu').test(clean))found.push(s);}const names=new Set();let reportedShip=null;for(const m of clean.matchAll(/(?:pilot|piloten|char|character)\s*:\s*([\p{L}\p{N}' -]{3,37})(?=\s*[|,;]|$)/giu))names.add(m[1].trim());for(const m of clean.matchAll(/["“]([\p{L}\p{N}' -]{3,37})["”]/gu))if(!found.some(s=>s.name.toLowerCase()===m[1].toLowerCase()))names.add(m[1].trim());if(found.length===1&&clean.toLowerCase().startsWith(found[0].name.toLowerCase()+' ')){const rest=clean.slice(found[0].name.length).trim();for(const ship of ships){if(rest.toLowerCase().endsWith(' '+ship.toLowerCase())){const pilot=rest.slice(0,-ship.length).trim();if(/^[\p{L}\p{N}][\p{L}\p{N}' -]{2,36}$/u.test(pilot)){names.add(pilot);reportedShip=ship;}break;}}}const ids=[...text.matchAll(/showinfo:137[3-9]\/\/(\d{6,12})/g)].map(m=>Number(m[1]));return {systems:found,names:[...names].slice(0,10),ids:[...new Set(ids)].slice(0,10),reportedShip};}
function isClear(text,systems){let rest=text.toLowerCase();for(const s of systems)rest=rest.replace(s.name.toLowerCase(),' ');return /^(?:clear|clr|cleared|frei|blue|blues|all blue|all blues)[.!\s]*$/.test(rest.trim());}
function friendly(pilot,own,friends){return pilot.id===own.id||friends.has(pilot.id)||Boolean(own.alliance_id&&pilot.alliance_id===own.alliance_id);}
function shipCounts(kills,id,now=Date.now()){const seen=new Set(),counts=new Map();let samples=0,oldest=null,newest=null;for(const k of kills){if(seen.has(k.killmail_id))continue;seen.add(k.killmail_id);const t=Date.parse(k.killmail_time);if(!Number.isFinite(t)||t>now||now-t>90*86400000)continue;const actor=k.victim?.character_id===id?k.victim:k.attackers?.find(a=>a.character_id===id);if(!Number.isSafeInteger(actor?.ship_type_id))continue;const type=actor.ship_type_id;if(type===670||type===33328)continue;counts.set(type,(counts.get(type)||0)+1);samples++;oldest=oldest===null?t:Math.min(oldest,t);newest=newest===null?t:Math.max(newest,t);}return {samples,oldest,newest,ships:[...counts].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,count])=>({id,count}))};}
function decoder(buffer){return new StringDecoder(buffer[0]===255&&buffer[1]===254?'utf16le':'utf8');}
module.exports={parseLine,localSystem,entities,isClear,friendly,shipCounts,decoder};
