const fs=require('node:fs/promises'),path=require('node:path');
const {parseLine,localSystem,entities,isClear,friendly,shipCounts,decoder}=require('./intel-core.cjs');
const systems=require('./system-catalog.json'),ships=require('./ship-names.json');
class IntelService{
 constructor(notify){this.notify=notify;this.config={folder:'',channels:'',pilot:'',system:'',friends:'',radius:5,autoLocation:true};this.running=false;this.generation=0;this.files=new Map();this.alerts=[];this.seen=new Map();this.cache=new Map();this.queue=[];this.status='Ausgeschaltet';this.warning='';this.lastPoll=null;this.current=null;this.locationCheckedAt=null;this.locationAttempt=0;this.locationError='';this.kbQueue=Promise.resolve();this.kbLast=0;}
 state(){return {config:this.config,running:this.running,status:this.status,warning:this.warning,current:this.current?.name||null,locationCheckedAt:this.locationCheckedAt,locationError:this.locationError,lastPoll:this.lastPoll,alerts:this.alerts};}
 emit(){this.notify(this.state());}
 async json(url,options={}){const r=await fetch(url,{...options,headers:{'User-Agent':'EVE-Control/1.3.0 https://github.com/cptdreca/eve-control','Accept-Encoding':'gzip','X-Compatibility-Date':'2026-08-23',...options.headers},signal:AbortSignal.timeout(12000)});if(!r.ok){const e=new Error(`Datenquelle: HTTP ${r.status}`);e.status=r.status;throw e;}const data=await r.json();if(data?.error)throw Error(String(data.error).slice(0,150));return data;}
 async esi(route){const old=this.cache.get(route);if(old&&Date.now()-old.time<300000)return old.value;const value=await this.json(`https://esi.evetech.net${route}`);if(this.cache.size>1000)this.cache.clear();this.cache.set(route,{time:Date.now(),value});return value;}
 async names(list){if(!list.length)return {};try{return await this.json('https://esi.evetech.net/universe/ids/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(list)});}catch(e){if(e.status===404)return {};throw e;}}
 configure(input){if(this.running||this.starting)throw Error('Alarm zuerst stoppen.');const clean={...this.config};for(const k of ['channels','pilot','system','friends']){if(typeof input[k]!=='string'||input[k].length>(k==='friends'?5000:500))throw Error('Ungültige Einstellungen');clean[k]=input[k].trim();}if(input.autoLocation!==undefined){if(typeof input.autoLocation!=='boolean')throw Error('Ungültiger Standortmodus');clean.autoLocation=input.autoLocation;}this.config=clean;this.emit();return this.state();}
 async start(){if(this.running||this.starting)return this.state();if(!this.config.folder||!this.config.channels||!this.config.pilot||(!this.config.autoLocation&&!this.config.system))throw Error('Bitte alle Pflichtfelder ausfüllen.');this.starting=true;const gen=++this.generation;try{const friends=this.config.friends.split(/[\n,;]/).map(s=>s.trim()).filter(Boolean);if(friends.length>100)throw Error('Maximal 100 Freunde.');const names=await this.names([this.config.pilot,...friends]);const own=names.characters?.find(c=>c.name.toLowerCase()===this.config.pilot.toLowerCase());const system=systems.find(s=>s.name.toLowerCase()===this.config.system.toLowerCase());if(!own||(!this.config.autoLocation&&!system))throw Error('Eigener Charakter oder System nicht gefunden. Vollständige Namen verwenden.');const missing=friends.filter(n=>!names.characters?.some(c=>c.name.toLowerCase()===n.toLowerCase()));if(missing.length)throw Error(`Freunde nicht gefunden: ${missing.join(', ')}`);this.own={...own,...await this.esi(`/characters/${own.id}/`)};this.friendIds=new Set(names.characters.filter(c=>friends.some(f=>f.toLowerCase()===c.name.toLowerCase())).map(c=>c.id));if(gen!==this.generation)return this.state();this.current=this.config.autoLocation?null:system;this.locationCheckedAt=null;this.locationAttempt=0;this.locationError='';this.running=true;this.started=Date.now();this.files.clear();this.queue=[];this.seen.clear();this.warning='';this.status='Aktiv';await this.poll(true);if(this.running)this.timer=setInterval(()=>void this.poll(false),2000);this.emit();return this.state();}finally{this.starting=false;}}
 stop(){this.running=false;this.generation++;clearInterval(this.timer);if(this.config.autoLocation)this.current=null;this.queue=[];this.status='Ausgeschaltet';this.emit();return this.state();}
 async refreshLocation(gen){
  if(!this.config.autoLocation)return;
  this.locationAttempt=Date.now();
  try{
   if(!this.locationProvider)throw Error('Standortdienst nicht verfügbar.');
   const data=await this.locationProvider(this.own.id);
   if(!this.running||gen!==this.generation)return;
   const system=systems.find(s=>s.id===data.id);
   if(!system)throw Error('ESI-System nicht im lokalen Katalog gefunden.');
   this.current=system;this.locationCheckedAt=new Date().toISOString();this.locationError='';
  }catch(e){if(this.running&&gen===this.generation){this.current=null;this.locationError='Entfernungswarnung pausiert: '+e.message;}}
  this.emit();
 }
 locationReady(){return Boolean(this.current)&&(!this.config.autoLocation||(this.locationCheckedAt&&Date.now()-Date.parse(this.locationCheckedAt)<60000));}
 async poll(initial=false){if(this.polling||!this.running)return;this.polling=true;const gen=this.generation;try{if(this.config.autoLocation&&Date.now()-this.locationAttempt>=30000)await this.refreshLocation(gen);if(!this.running||gen!==this.generation)return;const names=(await fs.readdir(this.config.folder)).filter(n=>n.endsWith('.txt')).sort().reverse().slice(0,500);const channels=this.config.channels.split(/[\n,;]/).map(s=>s.trim().toLowerCase()).filter(Boolean);let watched=0;for(const name of names){if(!this.running||gen!==this.generation)break;const local=/^(Local|Lokal)_/i.test(name);if(!local&&!channels.some(c=>name.toLowerCase().startsWith(c+'_')))continue;const file=path.join(this.config.folder,name);const stat=await fs.stat(file);if(!stat.isFile()||Date.now()-stat.mtimeMs>86400000)continue;let state=this.files.get(file);if(!state||stat.size<state.pos){const handle=await fs.open(file,'r');try{const head=Buffer.alloc(Math.min(8192,stat.size));await handle.read(head,0,head.length,0);const header=decoder(head).write(head);const listener=header.match(/Listener\s*:\s*([^\r\n]+)/i)?.[1]?.trim();if(listener?.toLowerCase()!==this.config.pilot.toLowerCase())continue;state={pos:initial?stat.size:0,decoder:decoder(head),tail:''};this.files.set(file,state);}finally{await handle.close();}}if(!local)watched++;if(stat.size===state.pos)continue;const handle=await fs.open(file,'r');let text;try{const b=Buffer.alloc(Math.min(stat.size-state.pos,262144));const result=await handle.read(b,0,b.length,state.pos);state.pos+=result.bytesRead;text=state.tail+state.decoder.write(b.subarray(0,result.bytesRead));}finally{await handle.close();}const lines=text.split(/\r?\n/);state.tail=lines.pop().slice(-10000);for(const raw of lines){const line=parseLine(raw);if(!line||line.time<this.started-2000||Date.now()-line.time>300000||line.time>Date.now()+30000)continue;if(local){if(this.config.autoLocation)continue;const name=localSystem(line),s=systems.find(s=>s.name.toLowerCase()===name?.toLowerCase());if(s){this.current=s;this.emit();}}else if(line.speaker.toLowerCase()!==this.config.pilot.toLowerCase())this.enqueue({line,gen,channel:name.replace(/_\d{8}_.*$/,'')});}}
 this.lastPoll=new Date().toISOString();this.status=watched?`Aktiv · ${watched} Intel-Logdatei(en)`:'Kein aktuelles Intel-Log gefunden. Kanal öffnen und Chat-Logging aktivieren.';this.emit();}catch(e){this.warning=`Logzugriff fehlgeschlagen: ${e.message}`;this.emit();}finally{this.polling=false;}}
 enqueue(item){if(this.queue.length>=50){this.warning='Zu viele Meldungen: Warteschlange voll, Meldungen können fehlen.';this.emit();return;}this.queue.push(item);void this.drain();}
 async drain(){if(this.processing)return;this.processing=true;try{while(this.queue.length&&this.running){const item=this.queue.shift();if(item.gen!==this.generation||Date.now()-item.line.time>300000)continue;try{await this.process(item);}catch(e){this.warning=`Intel-Prüfung unvollständig: ${e.message}`;this.emit();}}}finally{this.processing=false;}}
 async process(item){if(!this.locationReady()){this.locationError='Entfernungswarnung pausiert: '+(this.current?'Standort veraltet. Warte auf ESI.':this.locationError.replace(/^Entfernungswarnung pausiert: /,'')||'Warte auf ESI-Standort.');this.emit();return;}const {line,gen}=item;const parsed=entities(line.text,systems,ships);if(isClear(line.text,parsed.systems))return;if(parsed.systems.length!==1){this.warning='Meldung ohne eindeutigen vollständigen Systemnamen erkannt. Bitte Kanal prüfen.';this.emit();return;}const system=parsed.systems[0],current=this.current;let distance;if(system.id===current.id)distance=0;else{try{const route=await this.esi(`/route/${current.id}/${system.id}/?flag=shortest`);if(!Array.isArray(route)||!route.length)throw Error('Keine Route');distance=route.length-1;}catch(e){if(e.status===404){this.warning=`Keine Sternentorroute nach ${system.name}; Entfernung unbekannt.`;this.emit();return;}throw e;}}if(distance>5)return;const n=await this.names(parsed.names);const pilots=[...(n.characters||[])];for(const id of parsed.ids)if(!pilots.some(p=>p.id===id)){try{pilots.push({id,name:(await this.esi(`/characters/${id}/`)).name});}catch{}}
 const targets=[];this.own={...this.own,...await this.esi(`/characters/${this.own.id}/`)};for(const p of pilots.slice(0,10)){try{const data=await this.esi(`/characters/${p.id}/`);if(!friendly({...p,...data},this.own,this.friendIds))targets.push({...p,relation:'Nicht in eigener Allianz/Freundesliste'});}catch{targets.push({...p,relation:'Zugehörigkeit unbekannt'});}}if(pilots.length&&!targets.length)return;if(!targets.length)targets.push({id:null,name:'Pilot nicht eindeutig erkannt',relation:'Unbestätigte Intel-Meldung'});for(const target of targets){if(!this.running||gen!==this.generation||Date.now()-line.time>300000||!this.locationReady()||this.current.id!==current.id)return;const key=`${target.id||line.text}|${system.id}`,last=this.seen.get(key);if(last&&Date.now()-last<120000)continue;this.seen.set(key,Date.now());if(this.seen.size>1000)this.seen.delete(this.seen.keys().next().value);const alert={id:require('node:crypto').randomUUID(),pilot:target.name,characterId:target.id,relation:target.relation,system:system.name,from:current.name,distance,time:new Date(line.time).toISOString(),text:line.text.slice(0,1500),channel:item.channel,reportedShip:parsed.reportedShip};this.alerts.unshift(alert);this.alerts=this.alerts.slice(0,100);this.emit();this.onAlert?.(alert);}}
 async killboard(id){if(!Number.isSafeInteger(id)||id<=0||!this.alerts.some(a=>a.characterId===id))throw Error('Pilot ist nicht in der Intel-Liste.');const key=`zkb:${id}`,cached=this.cache.get(key);if(cached&&Date.now()-cached.time<3600000)return cached.value;const task=this.kbQueue.catch(()=>{}).then(async()=>{const again=this.cache.get(key);if(again&&Date.now()-again.time<3600000)return again.value;await new Promise(r=>setTimeout(r,Math.max(0,1100-(Date.now()-this.kbLast))));this.kbLast=Date.now();const kills=await this.json(`https://zkillboard.com/api/characterID/${id}/`);if(!Array.isArray(kills))throw Error('Ungültige Killboard-Antwort');const recent=kills.slice(0,200);let missing=0;for(let i=0;i<recent.length;i++){const k=recent[i];if(!k.victim){if(i<20&&Number.isSafeInteger(k.killmail_id)&&/^[a-f0-9]{40}$/i.test(k.zkb?.hash||'')){try{recent[i]=await this.esi(`/killmails/${k.killmail_id}/${k.zkb.hash}/`);}catch{missing++;}}else missing++;}}const summary=shipCounts(recent,id);summary.ships=await Promise.all(summary.ships.map(async s=>({...s,name:(await this.esi(`/universe/types/${s.id}/`)).name})));summary.fetchedAt=new Date().toISOString();summary.url=`https://zkillboard.com/character/${id}/`;summary.inspected=recent.length;summary.missing=missing;this.cache.set(key,{time:Date.now(),value:summary});return summary;});this.kbQueue=task;return task;}
}
module.exports={IntelService};
